version: "3.8"

services:
  db:
    image: postgres:16
    container_name: qts_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: abino
      POSTGRES_PASSWORD: pg-pass
      POSTGRES_DB: em-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
